
server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080

## mysql
spring:
  datasource:
    driver: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/mydb
    username: myadmin
    password: 1gpdhslsl2


logging:
  level:
    com:
      example:
        board: DEBUG